services:
  batalha-naval-postgres:
    container_name: batalha-naval-postgres
    image: postgres:18.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
       - ./docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
    restart: unless-stopped
    networks:
      - app-private-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4.0
    container_name: rediscache
    command: redis-server --appendonly yes --requirepass "RedisPassword123!" 
    volumes:
      - redis-data:/data
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-private-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "RedisPassword123!", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
  postgres-data:

networks:
  app-private-network:
    driver: bridge
    name: app-private-network